title: LazyExchangeAdmin
description: 
baseurl:
author: June Castillote
github: https://github.com/junecastillote
about: IT Consultant, Messaging and Collaboration, Freelance Author, PowerShell Fanatic
disqus_shortname: lazyexchangeadmin
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
  authors:
    output: true

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/june.castillote"
    - icon: fa-twitter
      link: "https://twitter.com/junecastillote"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/junecastillote/"
    - icon: fa-github
      link: "https://github.com/junecastillote"
    - icon: fa-google-plus
      link: "mailto:june.castillote@gmail.com"

share:
  twitter_username: junecastillote
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://junecastillote.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
