# Site
name: "LazyExchangeAdmin"
title: "LazyExchangeAdmin"
description: "PowerShell, Exchange, Office 365, Automation"
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"
baseurl: ""
google_analytics: "UA-157526958-1"
disqus: "lazyexchangeadmin"
mailchimp-list: #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  leo:
    name: leo
    display_name: Leo Castillote
    avatar: assets/images/author/leo.jpg
    gravatar:
    email: leo.castillote@gmail.com
    web:
    twitter: https://twitter.com/leocastillote
    facebook: https://www.facebook.com/leocastillote
    linkedin: https://www.linkedin.com/in/leocastillote
    github: https://github.com/casleo
    description: "Former Technical VA and Blog/Content Ghost Writer. Honing skills in Technical Writing. Passionate and eager about learning new things."
  arman:
    name: arman
    display_name: Arman Castillote
    avatar: "assets/images/author/arman.jpg"
    gravatar:
    email: castillote.arman@gmail.com
    web:
    twitter: https://twitter.com/castillotearman
    facebook: https://www.facebook.com/dianne15arman
    linkedin: https://www.linkedin.com/in/acastillote
    github: https://github.com/acast15
    description: "An IT Specialist and aspiring Technical Writer. Optimistic and persistent in learning."
  dan:
    name: dan
    display_name: Mark Daniel Dimalanta
    avatar: "assets/images/author/dan.jpg"
    gravatar:
    email: danieldimalanta@gmail.com
    web:
    twitter: https://twitter.com/MrMrsDanJo
    facebook: https://facebook.com/myvie14
    linkedin: https://www.linkedin.com/in/dandimalanta
    github: https://github.com/danieldimalanta
    description: "An innovator at heart. Enjoys simplifying complex processes and automating routine tasks."
  june:
    name: June
    display_name: June Castillote
    avatar: "assets/images/author/june.jpg"
    gravatar:
    email: june.castillote@gmail.com
    web: https://www.lazyexchangeadmin.cyou
    twitter: https://twitter.com/junecastillote
    facebook:
    linkedin: https://www.linkedin.com/in/junecastillote
    github: https://github.com/junecastillote
    description: "IT Engineer, Consultant, Writer, Blogger, Coder"
  rahul:
    name: Rahul
    display_name: Rahul Kadamb
    avatar: "assets/images/author/rahul.jpg"
    gravatar:
    email:
    web: https://www.nucleustechnologies.com/
    twitter:
    facebook:
    linkedin: https://www.linkedin.com/in/rahul-kadamb
    github:
    description: "An IT Specialist, Freelance Writer, Tech Blogger"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Feature Post ("enabled" or "disabled")
featured_post: disabled

# Other
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3547937806324155"
adsense-data-ad-slot: "2483784576"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
