# Site
name: "LazyExchangeAdmin"
title: "LazyExchangeAdmin"
description: PowerShell, Exchange, Office 365, Automation
logo: 'assets/images/logo.png'
favicon: 'assets/images/logoonly.png'
baseurl:
google_analytics: 'UA-157526958-1'
disqus: 'lazyexchangeadmin'
mailchimp-list: #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dan:
    name: dan
    display_name: Mark Daniel Dimalanta
    avatar: 'assets/images/dan.jpg'
    gravatar:
    email: danieldimalanta@gmail.com
    web:
    twitter:
    facebook: https://facebook.com/myvie14
    linkedin: https://www.linkedin.com/in/dandimalanta/
    github: https://github.com/danieldimalanta
    description: "An innovator at heart. Enjoys simplifying complex processes and automating routine tasks."
  june:
    name: June
    display_name: June Castillote
    avatar: 'assets/images/june.jpg'
    gravatar:
    email: june.castillote@gmail.com
    web: https://www.lazyexchangeadmin.com
    twitter: https://twitter.com/junecastillote
    facebook: https://facebook.com/june.castillote
    linkedin: https://www.linkedin.com/in/junecastillote/
    github: https://github.com/junecastillote
    description: "IT Engineer, Consultant, Freelance Writer, Blogger, and Coder"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
